version: '3.9'

services:
  database:
    image: postgres
    container_name: database_api_prisma_jest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_prisma_jest
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: api_prisma_jest
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database    
    env_file:
      - .env      

volumes:
  pgdata:
    driver: local
